-- Sample data for jobs table
-- IMPORTANT: Uses the correct abbreviated branch names from your database: CSE, EC, EEE, ISE, ME
-- Alumni UUID: 55df469a-ec41-402d-968f-94ea2dc2c2bc (provided by user)

INSERT INTO public.jobs (
  title,
  company,
  description,
  requirements,
  responsibilities,
  location,
  job_type,
  experience_level,
  salary_min,
  salary_max,
  salary_currency,
  application_deadline,
  contact_email,
  contact_phone,
  website_url,
  eligible_branches,
  eligible_semesters,
  minimum_cgpa,
  required_skills,
  preferred_skills,
  application_instructions,
  application_url,
  application_email,
  posted_by_id,
  posted_by_name,
  posted_by_email
) VALUES
(
  'Software Engineer',
  'Google',
  'We are looking for a passionate Software Engineer to join our team. You will be working on cutting-edge technologies and building scalable solutions that impact millions of users worldwide.',
  '3+ years of experience in software development, Strong knowledge of algorithms and data structures, Experience with distributed systems',
  'Design and develop scalable software solutions, Collaborate with cross-functional teams, Participate in code reviews and mentoring',
  'Bangalore, Karnataka',
  'full-time',
  'mid',
  800000,
  1500000,
  'INR',
  '2024-12-31',
  'careers@google.com',
  '+91-9876543210',
  'https://careers.google.com',
  ARRAY['CSE', 'ISE'],
  ARRAY['6th Semester', '7th Semester', '8th Semester'],
  7.5,
  ARRAY['Java', 'Python', 'Algorithms', 'Data Structures'],
  ARRAY['Kubernetes', 'AWS', 'Machine Learning'],
  'Please send your resume and cover letter to the email address provided. Include "Software Engineer Application" in the subject line.',
  'https://careers.google.com/software-engineer',
  'careers@google.com',
  '55df469a-ec41-402d-968f-94ea2dc2c2bc', -- Alumni UUID provided
  'Rajesh Kumar',
  'rajesh.kumar@google.com'
),
(
  'Frontend Developer',
  'Microsoft',
  'Join our dynamic frontend team to build beautiful and responsive web applications. You will work with React, TypeScript, and modern web technologies.',
  '2+ years of React experience, Proficiency in TypeScript and JavaScript, Experience with modern CSS frameworks',
  'Develop user-facing web applications, Optimize applications for maximum speed and scalability, Collaborate with UX/UI designers',
  'Hyderabad, Telangana',
  'full-time',
  'mid',
  600000,
  1200000,
  'INR',
  '2024-11-30',
  'jobs@microsoft.com',
  '+91-9876543211',
  'https://careers.microsoft.com',
  ARRAY['CSE', 'ISE'],
  ARRAY['5th Semester', '6th Semester', '7th Semester', '8th Semester'],
  7.0,
  ARRAY['React', 'JavaScript', 'TypeScript', 'CSS'],
  ARRAY['Node.js', 'GraphQL', 'Redux'],
  'Apply through our careers portal and include your portfolio link. Mention "Frontend Developer Position" in your application.',
  'https://careers.microsoft.com/frontend-developer',
  'jobs@microsoft.com',
  '55df469a-ec41-402d-968f-94ea2dc2c2bc', -- Alumni UUID provided
  'Priya Sharma',
  'priya.sharma@microsoft.com'
),
(
  'Data Scientist',
  'Amazon',
  'We are seeking a talented Data Scientist to analyze large datasets and build machine learning models that drive business decisions.',
  'Strong background in statistics and mathematics, Experience with Python and R, Knowledge of machine learning algorithms',
  'Analyze large datasets to extract insights, Build predictive models, Present findings to stakeholders',
  'Mumbai, Maharashtra',
  'full-time',
  'mid',
  1000000,
  1800000,
  'INR',
  '2024-12-15',
  'data@amazon.com',
  '+91-9876543212',
  'https://amazon.jobs',
  ARRAY['CSE', 'EC'],
  ARRAY['7th Semester', '8th Semester'],
  8.0,
  ARRAY['Python', 'Machine Learning', 'SQL', 'Statistics'],
  ARRAY['TensorFlow', 'PyTorch', 'Big Data'],
  'Submit your application via our online portal with your GitHub profile and any relevant project links. Include your research experience.',
  'https://amazon.jobs/data-scientist',
  'data@amazon.com',
  '55df469a-ec41-402d-968f-94ea2dc2c2bc', -- Alumni UUID provided
  'Amit Singh',
  'amit.singh@amazon.com'
);
